# Generated by Django 5.2.14 on 2026-05-21 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
        ('projects', '0001_initial'),
        ('volunteers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150, unique=True)),
                ('item_type', models.CharField(choices=[('FOOD', 'Food'), ('WATER_EQUIPMENT', 'Water Equipment'), ('MEDICAL_SUPPLIES', 'Medical Supplies'), ('SHELTER_EQUIPMENT', 'Shelter Equipment'), ('EDUCATION_MATERIAL', 'Education Material'), ('OTHER', 'Other')], max_length=20)),
                ('quantity_available', models.IntegerField(default=0)),
                ('unit', models.CharField(max_length=20)),
                ('reorder_level', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='AidDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_distributed', models.IntegerField()),
                ('distribution_date', models.DateField()),
                ('distributed_by_volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='volunteers.volunteer')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='distributions', to='beneficiaries.household')),
                ('logged_by_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='distributions', to='projects.project')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='distributions', to='inventory.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INFLOW', 'Inflow'), ('OUTFLOW', 'Outflow')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='inventory.inventory')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
