# Generated by Django 5.2.14 on 2026-05-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('budget_pkr', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('SUSPENDED', 'Suspended')], default='PLANNED', max_length=20)),
                ('villages', models.ManyToManyField(related_name='projects', to='beneficiaries.village')),
            ],
        ),
    ]
