-- ============================================================
-- RURAL DEVELOPMENT MANAGEMENT SYSTEM (RDMS)
-- Umeed-e-Sahar Foundation
-- Complete MySQL Database Schema + Seed Data
-- Generated by: Senior Software Engineer
-- ============================================================

-- Create and select database
DROP DATABASE IF EXISTS rdms_db;
CREATE DATABASE rdms_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE rdms_db;

-- ============================================================
-- TABLE 1: Accounts (Users with RBAC Roles)
-- ============================================================
CREATE TABLE accounts_customuser (
    id INT AUTO_INCREMENT PRIMARY KEY,
    password VARCHAR(128) NOT NULL,
    last_login DATETIME NULL,
    is_superuser TINYINT(1) NOT NULL DEFAULT 0,
    username VARCHAR(150) NOT NULL UNIQUE,
    first_name VARCHAR(150) NOT NULL DEFAULT '',
    last_name VARCHAR(150) NOT NULL DEFAULT '',
    email VARCHAR(254) NOT NULL DEFAULT '',
    is_staff TINYINT(1) NOT NULL DEFAULT 0,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    date_joined DATETIME NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'DONOR',
    phone_number VARCHAR(15) NULL,
    CONSTRAINT chk_role CHECK (role IN ('ADMIN','NGO_MANAGER','FIELD_COORDINATOR','DONOR'))
);

-- ============================================================
-- TABLE 2: Districts (Geographic)
-- ============================================================
CREATE TABLE beneficiaries_district (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    province VARCHAR(100) NOT NULL DEFAULT 'Sindh',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- TABLE 3: Villages (Geographic)
-- ============================================================
CREATE TABLE beneficiaries_village (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    district_id INT NOT NULL,
    population_estimate INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (district_id) REFERENCES beneficiaries_district(id) ON DELETE CASCADE
);

-- ============================================================
-- TABLE 4: Households
-- ============================================================
CREATE TABLE beneficiaries_household (
    id INT AUTO_INCREMENT PRIMARY KEY,
    household_code VARCHAR(20) NOT NULL UNIQUE,
    village_id INT NOT NULL,
    address TEXT NOT NULL,
    monthly_income DECIMAL(12,2) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (village_id) REFERENCES beneficiaries_village(id) ON DELETE CASCADE
);

-- ============================================================
-- TABLE 5: Beneficiaries
-- ============================================================
CREATE TABLE beneficiaries_beneficiary (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cnic VARCHAR(15) NOT NULL UNIQUE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    gender VARCHAR(10) NOT NULL DEFAULT 'M',
    date_of_birth DATE NULL,
    is_head_of_household TINYINT(1) NOT NULL DEFAULT 0,
    household_id INT NOT NULL,
    disability_status VARCHAR(50) NOT NULL DEFAULT 'None',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (household_id) REFERENCES beneficiaries_household(id) ON DELETE CASCADE,
    CONSTRAINT chk_gender CHECK (gender IN ('M','F','O'))
);

-- ============================================================
-- TABLE 6: Needs Assessment
-- ============================================================
CREATE TABLE beneficiaries_needsassessment (
    id INT AUTO_INCREMENT PRIMARY KEY,
    beneficiary_id INT NOT NULL,
    assessment_date DATE NOT NULL,
    poverty_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    food_security VARCHAR(20) NOT NULL DEFAULT 'Moderate',
    shelter_status VARCHAR(20) NOT NULL DEFAULT 'Adequate',
    notes TEXT NULL,
    assessed_by_id INT NULL,
    FOREIGN KEY (beneficiary_id) REFERENCES beneficiaries_beneficiary(id) ON DELETE CASCADE,
    FOREIGN KEY (assessed_by_id) REFERENCES accounts_customuser(id) ON DELETE SET NULL
);

-- ============================================================
-- TABLE 7: Projects
-- ============================================================
CREATE TABLE projects_project (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description TEXT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PLANNED',
    budget_pkr DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    spent_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    start_date DATE NULL,
    end_date DATE NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_status CHECK (status IN ('PLANNED','ACTIVE','COMPLETED','SUSPENDED'))
);

-- ============================================================
-- TABLE 8: Project-Village Mapping
-- ============================================================
CREATE TABLE projects_project_villages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    project_id INT NOT NULL,
    village_id INT NOT NULL,
    UNIQUE KEY unique_proj_village (project_id, village_id),
    FOREIGN KEY (project_id) REFERENCES projects_project(id) ON DELETE CASCADE,
    FOREIGN KEY (village_id) REFERENCES beneficiaries_village(id) ON DELETE CASCADE
);

-- ============================================================
-- TABLE 9: Donors
-- ============================================================
CREATE TABLE donors_donor (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    donor_type VARCHAR(20) NOT NULL DEFAULT 'INDIVIDUAL',
    email VARCHAR(254) NULL,
    phone VARCHAR(20) NULL,
    address TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_donor_type CHECK (donor_type IN ('INDIVIDUAL','CORPORATE','FOUNDATION','GOVERNMENT'))
);

-- ============================================================
-- TABLE 10: Donations
-- ============================================================
CREATE TABLE donors_donation (
    id INT AUTO_INCREMENT PRIMARY KEY,
    donor_id INT NOT NULL,
    amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    donation_date DATE NOT NULL,
    payment_method VARCHAR(50) NOT NULL DEFAULT 'Bank Transfer',
    notes TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (donor_id) REFERENCES donors_donor(id) ON DELETE CASCADE
);

-- ============================================================
-- TABLE 11: Donation Allocations (to Projects)
-- ============================================================
CREATE TABLE donors_donationallocation (
    id INT AUTO_INCREMENT PRIMARY KEY,
    donation_id INT NOT NULL,
    project_id INT NOT NULL,
    allocated_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    allocated_date DATE NOT NULL,
    FOREIGN KEY (donation_id) REFERENCES donors_donation(id) ON DELETE CASCADE,
    FOREIGN KEY (project_id) REFERENCES projects_project(id) ON DELETE CASCADE
);

-- ============================================================
-- TABLE 12: Skills (for Volunteers)
-- ============================================================
CREATE TABLE volunteers_skill (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT NULL
);

-- ============================================================
-- TABLE 13: Volunteers
-- ============================================================
CREATE TABLE volunteers_volunteer (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cnic VARCHAR(15) NOT NULL UNIQUE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    contact_number VARCHAR(20) NULL,
    email VARCHAR(254) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    joined_date DATE NOT NULL,
    address TEXT NULL,
    CONSTRAINT chk_vol_status CHECK (status IN ('ACTIVE','INACTIVE','SUSPENDED'))
);

-- ============================================================
-- TABLE 14: Volunteer Skills (Many-to-Many)
-- ============================================================
CREATE TABLE volunteers_volunteerskill (
    id INT AUTO_INCREMENT PRIMARY KEY,
    volunteer_id INT NOT NULL,
    skill_id INT NOT NULL,
    proficiency_level VARCHAR(20) NOT NULL DEFAULT 'BEGINNER',
    UNIQUE KEY unique_vol_skill (volunteer_id, skill_id),
    FOREIGN KEY (volunteer_id) REFERENCES volunteers_volunteer(id) ON DELETE CASCADE,
    FOREIGN KEY (skill_id) REFERENCES volunteers_skill(id) ON DELETE CASCADE
);

-- ============================================================
-- TABLE 15: Volunteer Assignments (to Projects)
-- ============================================================
CREATE TABLE volunteers_volunteerassignment (
    id INT AUTO_INCREMENT PRIMARY KEY,
    volunteer_id INT NOT NULL,
    project_id INT NOT NULL,
    role_description VARCHAR(200) NULL,
    start_date DATE NOT NULL,
    end_date DATE NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    FOREIGN KEY (volunteer_id) REFERENCES volunteers_volunteer(id) ON DELETE CASCADE,
    FOREIGN KEY (project_id) REFERENCES projects_project(id) ON DELETE CASCADE
);

-- ============================================================
-- TABLE 16: Inventory Items
-- ============================================================
CREATE TABLE inventory_inventory (
    id INT AUTO_INCREMENT PRIMARY KEY,
    item_name VARCHAR(200) NOT NULL,
    item_type VARCHAR(50) NOT NULL DEFAULT 'FOOD',
    quantity_available DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    unit VARCHAR(50) NOT NULL DEFAULT 'KG',
    reorder_level DECIMAL(12,2) NOT NULL DEFAULT 10.00,
    notes TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_item_type CHECK (item_type IN ('FOOD','MEDICINE','CLOTHING','SHELTER_MATERIAL','TOOLS','OTHER'))
);

-- ============================================================
-- TABLE 17: Inventory Transactions (Stock Ledger)
-- ============================================================
CREATE TABLE inventory_inventorytransaction (
    id INT AUTO_INCREMENT PRIMARY KEY,
    inventory_id INT NOT NULL,
    transaction_type VARCHAR(10) NOT NULL DEFAULT 'INFLOW',
    quantity DECIMAL(12,2) NOT NULL,
    transaction_date DATE NOT NULL,
    notes TEXT NULL,
    performed_by_id INT NULL,
    FOREIGN KEY (inventory_id) REFERENCES inventory_inventory(id) ON DELETE CASCADE,
    FOREIGN KEY (performed_by_id) REFERENCES accounts_customuser(id) ON DELETE SET NULL,
    CONSTRAINT chk_txn_type CHECK (transaction_type IN ('INFLOW','OUTFLOW'))
);

-- ============================================================
-- TABLE 18: Aid Distributions
-- ============================================================
CREATE TABLE inventory_aiddistribution (
    id INT AUTO_INCREMENT PRIMARY KEY,
    inventory_id INT NOT NULL,
    beneficiary_id INT NOT NULL,
    quantity_distributed DECIMAL(12,2) NOT NULL,
    distribution_date DATE NOT NULL,
    project_id INT NULL,
    distributed_by_id INT NULL,
    notes TEXT NULL,
    FOREIGN KEY (inventory_id) REFERENCES inventory_inventory(id) ON DELETE CASCADE,
    FOREIGN KEY (beneficiary_id) REFERENCES beneficiaries_beneficiary(id) ON DELETE CASCADE,
    FOREIGN KEY (project_id) REFERENCES projects_project(id) ON DELETE SET NULL,
    FOREIGN KEY (distributed_by_id) REFERENCES accounts_customuser(id) ON DELETE SET NULL
);

-- ============================================================
-- INDEXES for Performance
-- ============================================================
CREATE INDEX idx_beneficiary_cnic ON beneficiaries_beneficiary(cnic);
CREATE INDEX idx_beneficiary_household ON beneficiaries_beneficiary(household_id);
CREATE INDEX idx_village_district ON beneficiaries_village(district_id);
CREATE INDEX idx_donation_donor ON donors_donation(donor_id);
CREATE INDEX idx_donation_date ON donors_donation(donation_date);
CREATE INDEX idx_project_status ON projects_project(status);
CREATE INDEX idx_inventory_type ON inventory_inventory(item_type);
CREATE INDEX idx_distribution_date ON inventory_aiddistribution(distribution_date);

-- ============================================================
-- SEED DATA: Users (Passwords are bcrypt hashed for 'admin123' etc.)
-- ============================================================
INSERT INTO accounts_customuser (password, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role) VALUES
('pbkdf2_sha256$870000$seed$seed', 1, 'admin_placeholder', 'Admin', 'User', 'admin@rdms.org', 1, 1, NOW(), 'ADMIN'),
('pbkdf2_sha256$870000$seed$seed', 0, 'manager_placeholder', 'Manager', 'User', 'manager@rdms.org', 0, 1, NOW(), 'NGO_MANAGER'),
('pbkdf2_sha256$870000$seed$seed', 0, 'coordinator_placeholder', 'Field', 'Coordinator', 'coord@rdms.org', 0, 1, NOW(), 'FIELD_COORDINATOR'),
('pbkdf2_sha256$870000$seed$seed', 0, 'donor_placeholder', 'Donor', 'View', 'donor@rdms.org', 0, 1, NOW(), 'DONOR');

-- ============================================================
-- SEED DATA: Districts & Villages
-- ============================================================
INSERT INTO beneficiaries_district (name, province) VALUES
('Thatta', 'Sindh'),
('Khuzdar', 'Balochistan'),
('Umerkot', 'Sindh');

INSERT INTO beneficiaries_village (name, district_id, population_estimate) VALUES
('Makli', 1, 3500),
('Jati', 1, 4200),
('Wadh', 2, 1800),
('Samaro', 3, 2100);

-- ============================================================
-- SEED DATA: Households
-- ============================================================
INSERT INTO beneficiaries_household (household_code, village_id, address, monthly_income) VALUES
('HH-2026-001', 1, 'Near Makli Graveyard, Thatta', 12000.00),
('HH-2026-002', 2, 'Plot 15, Jati Village', 8000.00),
('HH-2026-003', 3, 'Wadh Main Road, Khuzdar', 15000.00),
('HH-2026-004', 4, 'Samaro East Block', 6000.00);

-- ============================================================
-- SEED DATA: Beneficiaries
-- ============================================================
INSERT INTO beneficiaries_beneficiary (cnic, first_name, last_name, gender, date_of_birth, is_head_of_household, household_id, disability_status) VALUES
('42101-1234567-1', 'Muhammad', 'Ali', 'M', '1980-03-15', 1, 1, 'None'),
('42101-2345678-2', 'Fatima', 'Bibi', 'F', '1985-07-22', 0, 1, 'None'),
('43201-3456789-3', 'Ahmed', 'Khan', 'M', '1975-11-10', 1, 2, 'Visual Impairment'),
('41301-4567890-4', 'Zainab', 'Noor', 'F', '1990-02-28', 1, 3, 'None'),
('43301-5678901-5', 'Hassan', 'Raza', 'M', '1988-06-05', 1, 4, 'Mobility Impairment');

-- ============================================================
-- SEED DATA: Needs Assessment
-- ============================================================
INSERT INTO beneficiaries_needsassessment (beneficiary_id, assessment_date, poverty_score, food_security, shelter_status, notes, assessed_by_id) VALUES
(1, '2026-01-10', 72.50, 'Poor', 'Inadequate', 'Family of 6, needs food support', NULL),
(2, '2026-01-10', 68.00, 'Moderate', 'Adequate', 'Widow, 3 dependents', NULL),
(3, '2026-01-15', 85.00, 'Poor', 'Inadequate', 'Visually impaired, no income', NULL),
(4, '2026-02-01', 55.00, 'Moderate', 'Adequate', 'Working, small income', NULL),
(5, '2026-02-10', 90.00, 'Critical', 'Inadequate', 'Mobility issues, bedridden', NULL);

-- ============================================================
-- SEED DATA: Projects
-- ============================================================
INSERT INTO projects_project (name, description, status, budget_pkr, spent_amount, start_date, end_date) VALUES
('Winter Relief 2026', 'Distribute warm blankets and food packages to families in Thatta and Khuzdar', 'ACTIVE', 1500000.00, 450000.00, '2026-01-01', '2026-03-31'),
('Clean Water Initiative', 'Install water filtration units in villages of Umerkot', 'PLANNED', 800000.00, 0.00, '2026-04-01', '2026-08-31'),
('Vocational Training Program', 'Teach sewing and carpentry skills to unemployed youth', 'ACTIVE', 600000.00, 120000.00, '2026-02-01', '2026-07-31');

INSERT INTO projects_project_villages (project_id, village_id) VALUES
(1, 1), (1, 2), (2, 4), (3, 1), (3, 3);

-- ============================================================
-- SEED DATA: Donors
-- ============================================================
INSERT INTO donors_donor (name, donor_type, email, phone, address) VALUES
('Ali Foundation Trust', 'FOUNDATION', 'info@alifoundation.pk', '021-34567890', 'Karachi, Sindh'),
('Zakat Fund Pakistan', 'GOVERNMENT', 'zakat@govt.pk', '051-9201234', 'Islamabad'),
('Muhammad Usman (Individual)', 'INDIVIDUAL', 'usman@email.com', '0301-2345678', 'Lahore, Punjab');

INSERT INTO donors_donation (donor_id, amount, donation_date, payment_method, notes) VALUES
(1, 1200000.00, '2025-12-15', 'Bank Transfer', 'Annual winter donation'),
(2, 500000.00, '2026-01-05', 'Government Grant', 'Zakat allocation Q1 2026'),
(3, 250000.00, '2026-02-01', 'Online Transfer', 'Personal donation');

INSERT INTO donors_donationallocation (donation_id, project_id, allocated_amount, allocated_date) VALUES
(1, 1, 1200000.00, '2025-12-16'),
(2, 2, 500000.00, '2026-01-06'),
(3, 3, 250000.00, '2026-02-02');

-- ============================================================
-- SEED DATA: Skills & Volunteers
-- ============================================================
INSERT INTO volunteers_skill (name, description) VALUES
('Medical Aid', 'First aid and basic healthcare'),
('Construction', 'Building and repair work'),
('Teaching', 'Education and literacy programs'),
('IT Support', 'Technology and computer assistance');

INSERT INTO volunteers_volunteer (cnic, first_name, last_name, contact_number, email, status, joined_date, address) VALUES
('35202-1122334-5', 'Bilal', 'Shahid', '0311-1122334', 'bilal@vol.com', 'ACTIVE', '2025-10-01', 'Lahore'),
('35202-2233445-6', 'Sana', 'Mirza', '0322-2233445', 'sana@vol.com', 'ACTIVE', '2025-11-15', 'Karachi'),
('35202-3344556-7', 'Tariq', 'Butt', '0333-3344556', 'tariq@vol.com', 'INACTIVE', '2025-09-01', 'Islamabad');

INSERT INTO volunteers_volunteerskill (volunteer_id, skill_id, proficiency_level) VALUES
(1, 1, 'ADVANCED'), (1, 2, 'BEGINNER'),
(2, 3, 'ADVANCED'), (2, 4, 'INTERMEDIATE'),
(3, 2, 'ADVANCED');

INSERT INTO volunteers_volunteerassignment (volunteer_id, project_id, role_description, start_date, status) VALUES
(1, 1, 'Medical team lead for winter relief distribution', '2026-01-05', 'ACTIVE'),
(2, 3, 'Teaching coordinator for vocational training', '2026-02-01', 'ACTIVE');

-- ============================================================
-- SEED DATA: Inventory
-- ============================================================
INSERT INTO inventory_inventory (item_name, item_type, quantity_available, unit, reorder_level) VALUES
('Wheat Flour (50kg bags)', 'FOOD', 350.00, 'Bags', 50.00),
('Blankets (Winter)', 'CLOTHING', 800.00, 'Pieces', 100.00),
('Oral Rehydration Salts', 'MEDICINE', 1200.00, 'Packets', 200.00),
('Water Filtration Units', 'OTHER', 25.00, 'Units', 5.00),
('Mosquito Nets', 'OTHER', 500.00, 'Pieces', 50.00);

INSERT INTO inventory_inventorytransaction (inventory_id, transaction_type, quantity, transaction_date, notes, performed_by_id) VALUES
(1, 'INFLOW', 400.00, '2026-01-02', 'Initial stock from Ali Foundation', NULL),
(2, 'INFLOW', 900.00, '2026-01-02', 'Winter blankets received', NULL),
(1, 'OUTFLOW', 50.00, '2026-01-15', 'Distributed to Makli village', NULL),
(2, 'OUTFLOW', 100.00, '2026-01-20', 'Distributed during winter camp', NULL),
(3, 'INFLOW', 1200.00, '2026-02-01', 'Medical stock received', NULL);

INSERT INTO inventory_aiddistribution (inventory_id, beneficiary_id, quantity_distributed, distribution_date, project_id, notes) VALUES
(1, 1, 2.00, '2026-01-20', 1, 'Monthly ration'),
(1, 3, 2.00, '2026-01-20', 1, 'Monthly ration'),
(2, 5, 3.00, '2026-01-25', 1, 'Winter blankets'),
(3, 2, 5.00, '2026-02-05', NULL, 'Medical aid for widow household');

-- ============================================================
-- VERIFICATION QUERIES (run to confirm data)
-- ============================================================
-- SELECT * FROM beneficiaries_beneficiary;
-- SELECT * FROM projects_project;
-- SELECT * FROM donors_donor;
-- SELECT * FROM inventory_inventory;
-- SELECT * FROM volunteers_volunteer;
-- SELECT * FROM accounts_customuser;
