# Generated by Django 5.2.14 on 2026-05-21 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('province', models.CharField(choices=[('SINDH', 'Sindh'), ('BALOCHISTAN', 'Balochistan'), ('PUNJAB', 'Punjab'), ('KPK', 'KPK')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_code', models.CharField(max_length=50, unique=True)),
                ('family_income_pkr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('water_source', models.CharField(max_length=100)),
                ('is_widow_headed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnic', models.CharField(max_length=15, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_head_of_household', models.BooleanField(default=False)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='beneficiaries.household')),
            ],
        ),
        migrations.CreateModel(
            name='NeedsAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField()),
                ('poverty_score', models.IntegerField()),
                ('housing_condition', models.CharField(max_length=100)),
                ('primary_need', models.CharField(choices=[('WATER', 'Water'), ('FOOD', 'Food'), ('MEDICAL', 'Medical'), ('EDUCATION', 'Education'), ('SHELTER', 'Shelter'), ('INCOME', 'Income')], max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('assessed_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='beneficiaries.household')),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gps_coordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('population_estimate', models.IntegerField(default=0)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='villages', to='beneficiaries.district')),
            ],
            options={
                'unique_together': {('name', 'district')},
            },
        ),
        migrations.AddField(
            model_name='household',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='households', to='beneficiaries.village'),
        ),
    ]
