# Generated by Django 5.2.14 on 2026-05-21 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('donor_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('CORPORATE', 'Corporate'), ('NGO_PARTNER', 'NGO Partner'), ('INTERNATIONAL', 'International')], max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('donation_type', models.CharField(choices=[('CASH', 'Cash'), ('IN_KIND', 'In-Kind')], max_length=10)),
                ('item_description', models.CharField(blank=True, max_length=255, null=True)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='donations', to='donors.donor')),
            ],
        ),
        migrations.CreateModel(
            name='DonationAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('allocated_date', models.DateField()),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='allocations', to='donors.donation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='allocations', to='projects.project')),
            ],
            options={
                'unique_together': {('donation', 'project')},
            },
        ),
    ]
